/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.itson.GUI;

/**
 *
 * @author koine
 */
public class DlgRegistroVehiculo extends javax.swing.JDialog {

    /**
     * Creates new form DlgRegistroVehiculo
     */
    public DlgRegistroVehiculo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblDatosVehiculo = new javax.swing.JLabel();
        lblVehiculo = new javax.swing.JLabel();
        lblNoSerie = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblLinea = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        txtNoSerie = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtLinea = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        cbxVehiculo = new javax.swing.JComboBox<>();
        lblRegistroVehiculo = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        lblVaciar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(249, 143, 143));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(251, 183, 183));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDatosVehiculo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDatosVehiculo.setText("Datos del vehículo");
        jPanel3.add(lblDatosVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        lblVehiculo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblVehiculo.setText("Vehículo:");
        jPanel3.add(lblVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        lblNoSerie.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNoSerie.setText("No.Serie:");
        jPanel3.add(lblNoSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        lblMarca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMarca.setText("Marca:");
        jPanel3.add(lblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        lblLinea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLinea.setText("Línea:");
        jPanel3.add(lblLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        lblColor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblColor.setText("Color:");
        jPanel3.add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        lblModelo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblModelo.setText("Modelo:");
        jPanel3.add(lblModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        txtNoSerie.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(txtNoSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 160, 30));

        txtMarca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 160, 30));

        txtLinea.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(txtLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 160, 30));

        txtColor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 160, 30));

        txtModelo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 160, 30));

        cbxVehiculo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbxVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Automovil" }));
        jPanel3.add(cbxVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 120, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 580, 270));

        lblRegistroVehiculo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblRegistroVehiculo.setText("Registro de Vehículo");
        jPanel2.add(lblRegistroVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        btnRegresar.setBackground(new java.awt.Color(212, 100, 107));
        btnRegresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        jPanel2.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 140, 50));

        btnRegistrar.setBackground(new java.awt.Color(212, 100, 107));
        btnRegistrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        jPanel2.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 150, 50));

        lblVaciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblVaciar.setForeground(new java.awt.Color(156, 51, 57));
        lblVaciar.setText("Vaciar");
        jPanel2.add(lblVaciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 640, 440));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgRegistroVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgRegistroVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgRegistroVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgRegistroVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgRegistroVehiculo dialog = new DlgRegistroVehiculo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbxVehiculo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblDatosVehiculo;
    private javax.swing.JLabel lblLinea;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblNoSerie;
    private javax.swing.JLabel lblRegistroVehiculo;
    private javax.swing.JLabel lblVaciar;
    private javax.swing.JLabel lblVehiculo;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtLinea;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNoSerie;
    // End of variables declaration//GEN-END:variables
}
