/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.GUI;

/**
 * Clase que muestra las dos opciones de placa: Vehículo Nuevo y Vehículo Usado.
 *
 * @author Michell Cedano - 233230, Magda Ramírez - 233523
 */
public class FrmTramitePlaca extends javax.swing.JFrame {

    /**
     * Método que crea el Form FrmTramitePlaca.
     */
    public FrmTramitePlaca() {
        initComponents();
        setTitle("PLACA");
    }

    /**
     * Método que muestra la pantalla de registro vehículo.
     */
    private void mostrarPantallaRegistroVehiculo() {
        this.dispose();
        DlgRegistroVehiculo registroVehiculo = new DlgRegistroVehiculo(this, true);
        registroVehiculo.setVisible(true);
    }

    /**
     * Método que muestra la pantalla placa vehículo usado.
     */
    private void mostrarPantallaPlacaVehiculoUsado() {
        this.dispose();
        DlgPlacaVehiculoUsado placaVehiculoUsado = new DlgPlacaVehiculoUsado(this, true);
        placaVehiculoUsado.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnVehiculoNuevo = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnVehiculoUsado = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(249, 143, 143));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Trámite de Placa");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        jPanel3.setBackground(new java.awt.Color(251, 183, 183));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Nuevo.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnVehiculoNuevo.setBackground(new java.awt.Color(251, 183, 183));
        btnVehiculoNuevo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVehiculoNuevo.setText("Vehículo Nuevo");
        btnVehiculoNuevo.setAlignmentX(1.0F);
        btnVehiculoNuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(212, 100, 107)));
        btnVehiculoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculoNuevoActionPerformed(evt);
            }
        });
        jPanel3.add(btnVehiculoNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 170, 60));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 170, 220));

        jPanel5.setBackground(new java.awt.Color(251, 183, 183));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Usado.png"))); // NOI18N
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnVehiculoUsado.setBackground(new java.awt.Color(251, 183, 183));
        btnVehiculoUsado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVehiculoUsado.setText("Vehículo Usado");
        btnVehiculoUsado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(212, 100, 107)));
        btnVehiculoUsado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculoUsadoActionPerformed(evt);
            }
        });
        jPanel5.add(btnVehiculoUsado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 170, 60));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 170, 220));

        btnRegresar.setBackground(new java.awt.Color(212, 100, 107));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/volver.png"))); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
/**
     * Botón que al hacerle clic abre la ventana DlgPlacaVehiculoUsado.
     *
     * @param evt objeto de evento de acción.
     */
    private void btnVehiculoUsadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculoUsadoActionPerformed
        // TODO add your handling code here:
        mostrarPantallaPlacaVehiculoUsado();
    }//GEN-LAST:event_btnVehiculoUsadoActionPerformed
    /**
     * Botón que al hacerle clic abre la ventana DlgRegistroVehiculo.
     *
     * @param evt objeto de evento de acción.
     */
    private void btnVehiculoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculoNuevoActionPerformed
        // TODO add your handling code here:
        mostrarPantallaRegistroVehiculo();
    }//GEN-LAST:event_btnVehiculoNuevoActionPerformed
    /**
     * Botón que al hacerle clic regresa a la ventana FrmRealizarTramite.
     *
     * @param evt objeto de evento de acción.
     */
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        FrmRealizarTramite realizarTramite = new FrmRealizarTramite();
        realizarTramite.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnVehiculoNuevo;
    private javax.swing.JButton btnVehiculoUsado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
